FROM node:10.13.0-alpine

RUN mkdir -p /var/www/app

WORKDIR /var/www/app

ARG NEXT_PUBLIC_FIREBASE_APIKEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN

COPY package.json ./
RUN npm install

ADD . /var/www/app

ENV NODE_ENV production
ENV PORT 3000

ENV NEXT_PUBLIC_FIREBASE_APIKEY=$NEXT_PUBLIC_FIREBASE_APIKEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN

RUN npm run build

ENTRYPOINT ["npm", "start"]